### ISSUE TITLE
혹시 라이믹스 기본 내장 회원모듈,커뮤니케이션 모듈의 스킨에 다크모드시 색반전이 가능하다면

### ISSUE THREAD

**Issue by wookho** [calvinsnax/rx-flextagram#4]
반영이 된다면  반길만한 일이 될텐데요. 일종의 표준 같은게 정해져서 서로 다른 레이아웃에서 각종 스킨들이 비슷한 반응을 하면 좋겠다는 생각을 해봤습니다.

표준이 중해지고 각 스킨에서 레이아웃에서 바뀌는 모드를 인식하게 하는게 맞습니다만 현재로서는 그 과정의 중간 단계에서 기본 스킨에만 대응을 할 수 있을지 한번 의견을 내어봅니다.

구조적으로 힘들다거나 일이 너무 많아진다면 그냥 모듈의 스킨에서 처리하는게 정답일 것 같습니다.

**Comment by calvinsnax** [comment]
레이아웃 상에서 일부 모듈 스킨에 대해 CSS를 이용한 강제 색반전이 가능하나, 말 그대로 색반전이기 때문에 여러모로 원하는 결과가 나오기 어려울 수 있습니다. 필터를 걸어 색반전을 하는 것이기 때문에 성능 이슈가 있을 수도 있구요.
장기적으로는 회원 모듈, 커뮤니케이션 모듈용 스킨도 계획 중입니다만, 현재 코어 자체가 급진적인 변화를 겪고 있기 때문에 섣불리 작업을 시도하면 변경점들을 따라가기 어려울 수도 있다고 판단하여 아직 진행하고 있지는 않습니다. 추후 람보님께서 진행 중이신 코어 자체지원 소셜로그인 모듈이 완성되면 준비해볼 수 있을 것 같습니다.

**Comment by bnu** [comment]
라이믹스에 배경색과 글자색 그리고 몇가지의 최소환된 수로 정의한 컬러셋을 CSS Variable로 내장하거나 라이믹스에서 유일하게 다크모드를 지원하는 에디터에서 해당 색상을 사용하도록 제안하는 것도 좋을 것 같습니다.

```css
:root {
  --rx-color-background: #fff;
  --rx-color-text: #212529;
}

.color_scheme_dark {
  --rx-color-background: #171717;
  --rx-color-text: #fafafa;
}
```
위와 같이 최소한의 배경/글자 색상을 비롯하여 몇 단계의 영역 등 구분에 사용하는 라인 또는 배경색 등에 사용할 수 있는 gray 계통의 색상 정도만 정의하여 공통으로 사용해도 아래 이미지와 같은 이질감은 크게 제거할 수 있고 앞으로도 다크 모드 등의 적용에 도움이 될 것 같습니다.

<img width="1013" alt="스크린샷" src="https://user-images.githubusercontent.com/53764/118969209-c3c3d400-b9a7-11eb-9609-5d7c99e85e46.png">
